# Generated by Django 5.2.2 on 2025-06-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tax_id',
        ),
    ]
