# Generated by Django 5.2.2 on 2025-06-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TVA rate (%) applied to all products for this company', max_digits=5),
        ),
    ]
