# Generated by Django 5.2.2 on 2025-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_currency_and_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='TVA rate (%) applied to all products for this company', max_digits=5),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
